services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password="calinpc"
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionString="Server=sqldata;Initial Catalog=Licirom;User Id=sa;Password=${SQL_SERVER_PASSWORD}"
    ports:
      - "8001:80"
      - "8000:443"
    volumes:
      - ~/.aspnet/https:/https:ro

  sqldata:
